import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { Space, Spin } from "antd";
import Databox from "../../Components/Databox";
import { useQuery } from "@apollo/client";

import {get_all  } from "../pages/api/Query/Query";
import MainHead from '../../Components/MainHead';
import { DataBoxdata  } from '@/Types/types';


export default function Home() {
  const {  loading, error, data } = useQuery(get_all);
  console.log(data, loading);
  return (
    <>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
<MainHead/>
    <div
      className="masonry"
      style={{
        display: loading ? "flex" : "inherit",
      }}
    >
      {loading == true && (
        <Space style={{ margin: "auto", height: "60vh" }} size="middle">
          <Spin size="large" />
        </Space>
      )}
      {loading == false &&
        data?.check_in.map((s:DataBoxdata,n:any) => {
          return (
            <div key={n} className="item">
              <Databox data={s} />
            </div>
          );
        })}
    </div>
  </>
  )
}
